graphAlgos: graph.o graphAlgos.o
	clang++ -std=c++11 -stdlib=libc++ -Weverything -o graphAlgos graph.o graphAlgos.o 

listAlgos: listAlgos.o
	clang++ -std=c++11 -stdlib=libc++ -Weverything -o listAlgos listAlgos.o